Added JUnit testing with BuiltBrokenModding/MinecraftJUnit
Created unit tests for ResLoc, EasyNBT, and ISerializableEnum
Tests will now run after each push instead of only pull requests
CarverBot's asset optimization will not leave a public discord notification anymore
Fixed withAny method in EasyNBT (thanks to tests)

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -5,6 +5,43 @@ on:
     branches: [ "dev/**" ]
 
 jobs:
+  check:
+    runs-on: ubuntu-latest
+    name: Check Pull Request's Quality
+    env:
+      GITHUB_USERNAME: ${{ github.actor }}
+      GITHUB_TOKEN: ${{ secrets.OPTIMIZATION_TOKEN }}
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Setup Java
+        uses: actions/setup-java@v4
+        with:
+          distribution: corretto
+          java-version: 8
+
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v3
+
+      - name: Prepare Workspace
+        run: chmod +x gradlew ; ./gradlew setupDecompWorkspace
+
+      - name: Check for Compilation
+        run: ./gradlew compileJava
+
+      - name: Run Unit Tests
+        run: ./gradlew test
+
+      - name: Test Report
+        uses: phoenix-actions/test-reporting@v15
+        id: test-report               # Set ID reference for step
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests            # Name of the check run which will be created
+          path: build/test-results/test/TEST-*.xml    # Path to test results
+          reporter: java-junit        # Format of test results
+
   notify-public-discord:
     continue-on-error: true
     name: Notify Public Discord
